version: "3.8"

services:
  backend:
    build: ./backend
    container_name: card-backend
    ports:
      - "5000:80"
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: card-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
